"""
generate_contrived_spectrum.py
==============================
Generates a contrived spectrum dataset that mimics power spectral density
(PSD) snapshots mapped to quantum circuit families.

APPROACH
--------
Rather than approximating distributions from marginals (which loses all
higher-order structure), each synthetic spectrum "session" is generated by
bootstrap-resampling feature vectors directly from the real circuit data.

This preserves entropy, collision probability, parity bias, ZZ correlations,
and all other statistics that actually distinguish the three circuit families.

The physical interpretation:
    - Each circuit run  ≈  one PSD snapshot (one measurement of the spectrum)
    - Each session      ≈  N snapshots collected over an observation window
    - Session feature   ≈  mean feature vector over those N snapshots
                           (like averaging many spectrum readings)

Output files go to data/spectrum/ and are drop-in compatible with
models/models.py -- same X, y, meta, featdicts structure as circuit data.

Usage (from spectrum/ directory):
    python3 generate_contrived_spectrum.py <config.yaml>

The yaml file uses the same format as main/circuit_configuration.yaml:
    qubit_range: [min, max]        # iterates from min to max (exclusive)
    labels: [iqp, clifford, ...]   # circuit families to process
    n_circuits: 1000               # used as n_sessions
    master_seed: 42
    snapshots_per_session: 50      # optional, defaults to 50
"""

import sys
from pathlib import Path
sys.path.append(str(Path(__file__).resolve().parent.parent))

import numpy as np
import yaml

_DATA_ROOT = Path(__file__).resolve().parent.parent / "data"

_MODE_DIRS = {
    "z_only":      (_DATA_ROOT / "quantum",          _DATA_ROOT / "spectrum"),
    "multi_basis": (_DATA_ROOT / "quantum_mb",        _DATA_ROOT / "spectrum_mb"),
    "shadows":     (_DATA_ROOT / "quantum_shadows",   _DATA_ROOT / "spectrum_shadows"),
}

# -- Config loading ----------------------------------------------------------

def load_cfg_from_yaml(path: str) -> dict:
    with open(path, "r") as f:
        data = yaml.safe_load(f)
    return {
        "families":              data["labels"],
        "qubit_range":           range(data["qubit_range"][0], data["qubit_range"][-1]),
        "shots_base":            data["shots_base"],
        "n_sessions":            data["n_circuits"],
        "snapshots_per_session": data.get("snapshots_per_session", 50),
        "master_seed":           data["master_seed"],
    }

# -- Data loading ------------------------------------------------------------

def load_circuit_features(family: str, n_qubits: int, shots: int, data_dir: Path):
    """
    Load X feature vectors for a given family and qubit count.
    shots is computed as shots_base * n_qubits^2.
    Returns X array of shape (n_samples, n_features).
    """
    pattern = f"circuitFamily_{family}_qubits{n_qubits}_*shotsPerDatapoint{shots}_*.npz"
    matches = sorted(data_dir.glob(pattern))
    if not matches:
        raise FileNotFoundError(
            f"No circuit files found for family='{family}', "
            f"n_qubits={n_qubits}, shots={shots} in {data_dir}.\n"
            f"Run generate_distributions.py first."
        )

    X_list = []
    for f in matches:
        data = np.load(f, allow_pickle=True)
        X_list.append(data['X'])

    X = np.concatenate(X_list, axis=0)
    print(f"  {family:<12} shots={shots:<5} loaded {X.shape[0]} circuit samples "
          f"from {len(matches)} file(s)  |  feature dim: {X.shape[1]}")
    return X


# -- Session generation ------------------------------------------------------

def generate_sessions(
    X_source: np.ndarray,
    n_sessions: int,
    snapshots_per_session: int,
    rng: np.random.Generator,
) -> np.ndarray:
    """
    Generate spectrum sessions by bootstrap-resampling from circuit features.

    Each session draws `snapshots_per_session` rows from X_source with
    replacement and averages them. This simulates a sensor collecting
    multiple PSD snapshots and summarising their statistics.

    Returns X_sessions of shape (n_sessions, n_features).
    """
    n_source, n_features = X_source.shape
    X_sessions = np.zeros((n_sessions, n_features), dtype=np.float64)

    for i in range(n_sessions):
        indices = rng.integers(0, n_source, size=snapshots_per_session)
        X_sessions[i] = X_source[indices].mean(axis=0)

    return X_sessions


# -- Main --------------------------------------------------------------------

def generate_contrived_spectrum(
    family: str,
    n_qubits: int,
    shots: int,
    n_sessions: int,
    snapshots_per_session: int,
    data_dir: Path,
    out_dir: Path,
    seed: int,
) -> Path:

    print(f"\n[{family} | {n_qubits} qubits | shots={shots} | "
          f"{n_sessions} sessions x {snapshots_per_session} snapshots]")

    X_source = load_circuit_features(family, n_qubits, shots, data_dir)

    rng = np.random.default_rng(seed)
    X_sessions = generate_sessions(X_source, n_sessions, snapshots_per_session, rng)

    y = np.array([f"spectrum_{family}"] * n_sessions)

    meta = np.array([{
        "family":                f"spectrum_{family}",
        "n_qubits":              n_qubits,
        "shots_per_datapoint":   shots,
        "session_index":         i,
        "snapshots_per_session": snapshots_per_session,
        "seed":                  seed,
    } for i in range(n_sessions)])

    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / (
        f"spectrum_contrived_{family}"
        f"_qubits{n_qubits}"
        f"_shots{shots}"
        f"_sessions{n_sessions}"
        f"_snapshots{snapshots_per_session}"
        f"_seed{seed}.npz"
    )

    np.savez(out_path, X=X_sessions, y=y, meta=meta)
    print(f"  Saved: {out_path.name}  |  X shape: {X_sessions.shape}")
    return out_path


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 generate_contrived_spectrum.py <config.yaml> [mode]")
        print("  mode: z_only (default) | multi_basis | shadows")
        sys.exit(1)

    mode = sys.argv[2] if len(sys.argv) >= 3 else "z_only"
    if mode not in _MODE_DIRS:
        print(f"Unknown mode '{mode}'. Choose from: {list(_MODE_DIRS)}")
        sys.exit(1)

    QUANTUM_DIR, OUT_DIR = _MODE_DIRS[mode]
    print(f"Mode: {mode}")

    cfg = load_cfg_from_yaml(sys.argv[1])
    families              = cfg["families"]
    qubit_range           = cfg["qubit_range"]
    shots_base            = cfg["shots_base"]
    n_sessions            = cfg["n_sessions"]
    snapshots_per_session = cfg["snapshots_per_session"]
    master_seed           = cfg["master_seed"]

    print(f"Generating contrived spectrum data")
    print(f"  Source: {QUANTUM_DIR}")
    print(f"  Output: {OUT_DIR}")

    rng_seed = master_seed
    generated = []

    for n_qubits in qubit_range:
        shots = shots_base * n_qubits ** 2

        if OUT_DIR.exists():
            stale = list(OUT_DIR.glob(f"spectrum_contrived_*qubits{n_qubits}*.npz"))
            for f in stale:
                f.unlink()
                print(f"  Removed stale file: {f.name}")

        for family in families:
            path = generate_contrived_spectrum(
                family                = family,
                n_qubits              = n_qubits,
                shots                 = shots,
                n_sessions            = n_sessions,
                snapshots_per_session = snapshots_per_session,
                data_dir              = QUANTUM_DIR,
                out_dir               = OUT_DIR,
                seed                  = rng_seed,
            )
            generated.append(path)
            rng_seed += 1

    print("\n-- Summary ---------------------------------------------------")
    for p in generated:
        print(f"  {p.name}")
    print("\nDone. Run run_spectrum_experiment.py to classify.")


if __name__ == "__main__":
    main()
